package com.anand.geeksforgeeks.test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public class FilesCopy {

	public static void main(String[] args) {
		String[] jarNames = new String[] {
				"C:\\Users\\anand\\.m2\\repository\\xerces\\xercesImpl\\2.11.0\\xercesImpl-2.11.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\xml-apis\\xml-apis\\1.4.01\\xml-apis-1.4.01.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\commons\\commons-pool2\\2.4.2\\commons-pool2-2.4.2.jar",
				"C:\\Users\\anand\\.m2\\repository\\net\\sourceforge\\jregex\\jregex\\1.2_01\\jregex-1.2_01.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\jdom\\jdom\\1.1\\jdom-1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\eqtechnologic\\eqube\\platform\\utils\\search\\7.0.0.3\\search-7.0.0.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\eqtechnologic\\eqube\\platform\\model\\modelutil\\7.0.0.25\\modelutil-7.0.0.25.jar",
				"C:\\Users\\anand\\.m2\\repository\\net\\sourceforge\\owlapi\\owlapi-distribution\\4.1.3\\owlapi-distribution-4.1.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\fasterxml\\jackson\\core\\jackson-core\\2.5.1\\jackson-core-2.5.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\fasterxml\\jackson\\core\\jackson-databind\\2.5.1\\jackson-databind-2.5.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\fasterxml\\jackson\\core\\jackson-annotations\\2.5.1\\jackson-annotations-2.5.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\tukaani\\xz\\1.5\\xz-1.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-model\\2.7.12\\sesame-model-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-util\\2.7.12\\sesame-util-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-api\\2.7.12\\sesame-rio-api-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-languages\\2.7.12\\sesame-rio-languages-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-datatypes\\2.7.12\\sesame-rio-datatypes-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-binary\\2.7.12\\sesame-rio-binary-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-n3\\2.7.12\\sesame-rio-n3-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-nquads\\2.7.12\\sesame-rio-nquads-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-ntriples\\2.7.12\\sesame-rio-ntriples-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-rdfjson\\2.7.12\\sesame-rio-rdfjson-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-rdfxml\\2.7.12\\sesame-rio-rdfxml-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-trix\\2.7.12\\sesame-rio-trix-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-turtle\\2.7.12\\sesame-rio-turtle-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\openrdf\\sesame\\sesame-rio-trig\\2.7.12\\sesame-rio-trig-2.7.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\github\\jsonld-java\\jsonld-java-sesame\\0.5.0\\jsonld-java-sesame-0.5.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\github\\jsonld-java\\jsonld-java\\0.5.0\\jsonld-java-0.5.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\httpcomponents\\httpclient-cache\\4.2.5\\httpclient-cache-4.2.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\slf4j\\jcl-over-slf4j\\1.7.7\\jcl-over-slf4j-1.7.7.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\semarglproject\\semargl-sesame\\0.6.1\\semargl-sesame-0.6.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\semarglproject\\semargl-core\\0.6.1\\semargl-core-0.6.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\semarglproject\\semargl-rdfa\\0.6.1\\semargl-rdfa-0.6.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\semarglproject\\semargl-rdf\\0.6.1\\semargl-rdf-0.6.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\net\\sf\\trove4j\\trove4j\\3.0.3\\trove4j-3.0.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\guava\\guava\\18.0\\guava-18.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\inject\\guice\\4.0\\guice-4.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\inject\\javax.inject\\1\\javax.inject-1.jar",
				"C:\\Users\\anand\\.m2\\repository\\aopalliance\\aopalliance\\1.0\\aopalliance-1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\inject\\extensions\\guice-assistedinject\\4.0\\guice-assistedinject-4.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\inject\\extensions\\guice-multibindings\\4.0\\guice-multibindings-4.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\code\\findbugs\\jsr305\\2.0.1\\jsr305-2.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-io\\commons-io\\2.4\\commons-io-2.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\lucene\\lucene-core\\5.5.2\\lucene-core-5.5.2.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\lucene\\lucene-analyzers-common\\5.5.2\\lucene-analyzers-common-5.5.2.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\eqtechnologic\\eqube\\platform\\utils\\common-util\\2.0.0.3\\common-util-2.0.0.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\eqtechnologic\\eqube\\platform\\utils\\logging\\2.1.0.3\\logging-2.1.0.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\eqtechnologic\\eqube\\platform\\utils\\adaptererrorcodeframework\\1.0.0.8\\adaptererrorcodeframework-1.0.0.8.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-client\\3.1.0\\hadoop-client-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-common\\3.1.0\\hadoop-common-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\commons\\commons-math3\\3.1.1\\commons-math3-3.1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-codec\\commons-codec\\1.11\\commons-codec-1.11.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-net\\commons-net\\3.6\\commons-net-3.6.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-collections\\commons-collections\\3.2.2\\commons-collections-3.2.2.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-servlet\\9.3.19.v20170502\\jetty-servlet-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-security\\9.3.19.v20170502\\jetty-security-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-webapp\\9.3.19.v20170502\\jetty-webapp-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-xml\\9.3.19.v20170502\\jetty-xml-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\servlet\\jsp\\jsp-api\\2.1\\jsp-api-2.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\sun\\jersey\\jersey-servlet\\1.19\\jersey-servlet-1.19.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-lang\\commons-lang\\2.6\\commons-lang-2.6.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-beanutils\\commons-beanutils\\1.9.3\\commons-beanutils-1.9.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\commons\\commons-configuration2\\2.1.1\\commons-configuration2-2.1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\commons\\commons-lang3\\3.4\\commons-lang3-3.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\re2j\\re2j\\1.1\\re2j-1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\code\\gson\\gson\\2.2.4\\gson-2.2.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-auth\\3.1.0\\hadoop-auth-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\nimbusds\\nimbus-jose-jwt\\4.41.1\\nimbus-jose-jwt-4.41.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\github\\stephenc\\jcip\\jcip-annotations\\1.0-1\\jcip-annotations-1.0-1.jar",
				"C:\\Users\\anand\\.m2\\repository\\net\\minidev\\json-smart\\2.3\\json-smart-2.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\net\\minidev\\accessors-smart\\1.2\\accessors-smart-1.2.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\ow2\\asm\\asm\\5.0.4\\asm-5.0.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\curator\\curator-client\\2.12.0\\curator-client-2.12.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\curator\\curator-recipes\\2.12.0\\curator-recipes-2.12.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\htrace\\htrace-core4\\4.1.0-incubating\\htrace-core4-4.1.0-incubating.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\commons\\commons-compress\\1.4.1\\commons-compress-1.4.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-simplekdc\\1.0.1\\kerb-simplekdc-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-client\\1.0.1\\kerb-client-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerby-config\\1.0.1\\kerby-config-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-core\\1.0.1\\kerb-core-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerby-pkix\\1.0.1\\kerby-pkix-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerby-asn1\\1.0.1\\kerby-asn1-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerby-util\\1.0.1\\kerby-util-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-common\\1.0.1\\kerb-common-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-crypto\\1.0.1\\kerb-crypto-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-util\\1.0.1\\kerb-util-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\token-provider\\1.0.1\\token-provider-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-admin\\1.0.1\\kerb-admin-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-server\\1.0.1\\kerb-server-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerb-identity\\1.0.1\\kerb-identity-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\kerby\\kerby-xdr\\1.0.1\\kerby-xdr-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\codehaus\\woodstox\\stax2-api\\3.1.4\\stax2-api-3.1.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\fasterxml\\woodstox\\woodstox-core\\5.0.3\\woodstox-core-5.0.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-hdfs-client\\3.1.0\\hadoop-hdfs-client-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\squareup\\okhttp\\okhttp\\2.7.5\\okhttp-2.7.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\squareup\\okio\\okio\\1.6.0\\okio-1.6.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-yarn-api\\3.1.0\\hadoop-yarn-api-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\xml\\bind\\jaxb-api\\2.2.11\\jaxb-api-2.2.11.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-yarn-client\\3.1.0\\hadoop-yarn-client-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-mapreduce-client-core\\3.1.0\\hadoop-mapreduce-client-core-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-yarn-common\\3.1.0\\hadoop-yarn-common-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-util\\9.3.19.v20170502\\jetty-util-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\sun\\jersey\\jersey-core\\1.19\\jersey-core-1.19.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\ws\\rs\\jsr311-api\\1.1.1\\jsr311-api-1.1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\sun\\jersey\\jersey-client\\1.19\\jersey-client-1.19.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\fasterxml\\jackson\\module\\jackson-module-jaxb-annotations\\2.7.8\\jackson-module-jaxb-annotations-2.7.8.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\fasterxml\\jackson\\jaxrs\\jackson-jaxrs-json-provider\\2.7.8\\jackson-jaxrs-json-provider-2.7.8.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\fasterxml\\jackson\\jaxrs\\jackson-jaxrs-base\\2.7.8\\jackson-jaxrs-base-2.7.8.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-mapreduce-client-jobclient\\3.1.0\\hadoop-mapreduce-client-jobclient-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-annotations\\3.1.0\\hadoop-annotations-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-mapreduce-client-app\\3.1.0\\hadoop-mapreduce-client-app-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-mapreduce-client-common\\3.1.0\\hadoop-mapreduce-client-common-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-yarn-server-web-proxy\\3.1.0\\hadoop-yarn-server-web-proxy-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\servlet\\javax.servlet-api\\3.1.0\\javax.servlet-api-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-yarn-server-common\\3.1.0\\hadoop-yarn-server-common-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-yarn-registry\\3.1.0\\hadoop-yarn-registry-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-daemon\\commons-daemon\\1.0.13\\commons-daemon-1.0.13.jar",
				"C:\\Users\\anand\\.m2\\repository\\dnsjava\\dnsjava\\2.1.7\\dnsjava-2.1.7.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\geronimo\\specs\\geronimo-jcache_1.0_spec\\1.0-alpha-1\\geronimo-jcache_1.0_spec-1.0-alpha-1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\ehcache\\ehcache\\3.3.1\\ehcache-3.3.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\zaxxer\\HikariCP-java7\\2.4.12\\HikariCP-java7-2.4.12.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\microsoft\\sqlserver\\mssql-jdbc\\6.2.1.jre7\\mssql-jdbc-6.2.1.jre7.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-server\\9.3.19.v20170502\\jetty-server-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-http\\9.3.19.v20170502\\jetty-http-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\jetty-io\\9.3.19.v20170502\\jetty-io-9.3.19.v20170502.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-mapreduce-client-shuffle\\3.1.0\\hadoop-mapreduce-client-shuffle-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hadoop\\hadoop-yarn-server-nodemanager\\3.1.0\\hadoop-yarn-server-nodemanager-3.1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\codehaus\\jettison\\jettison\\1.1\\jettison-1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\io\\dropwizard\\metrics\\metrics-core\\3.2.4\\metrics-core-3.2.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\sun\\jersey\\jersey-json\\1.19\\jersey-json-1.19.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\sun\\xml\\bind\\jaxb-impl\\2.2.3-1\\jaxb-impl-2.2.3-1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\codehaus\\jackson\\jackson-jaxrs\\1.9.2\\jackson-jaxrs-1.9.2.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\codehaus\\jackson\\jackson-xc\\1.9.2\\jackson-xc-1.9.2.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\sun\\jersey\\contribs\\jersey-guice\\1.19\\jersey-guice-1.19.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\fusesource\\leveldbjni\\leveldbjni-all\\1.8\\leveldbjni-all-1.8.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\protobuf\\protobuf-java\\2.5.0\\protobuf-java-2.5.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\avro\\avro\\1.7.7\\avro-1.7.7.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\codehaus\\jackson\\jackson-core-asl\\1.9.13\\jackson-core-asl-1.9.13.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\codehaus\\jackson\\jackson-mapper-asl\\1.9.13\\jackson-mapper-asl-1.9.13.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\thoughtworks\\paranamer\\paranamer\\2.3\\paranamer-2.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\xerial\\snappy\\snappy-java\\1.0.5\\snappy-java-1.0.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\google\\inject\\extensions\\guice-servlet\\4.0\\guice-servlet-4.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\io\\netty\\netty\\3.10.5.Final\\netty-3.10.5.Final.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-cli\\commons-cli\\1.4\\commons-cli-1.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\hive-jdbc\\1.0.1\\hive-jdbc-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\hive-common\\1.0.1\\hive-common-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\ant\\ant\\1.9.1\\ant-1.9.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\ant\\ant-launcher\\1.9.1\\ant-launcher-1.9.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\hive-service\\1.0.1\\hive-service-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\net\\sf\\jpam\\jpam\\1.1\\jpam-1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\eclipse\\jetty\\aggregate\\jetty-all\\7.6.0.v20120127\\jetty-all-7.6.0.v20120127.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\servlet\\servlet-api\\2.5\\servlet-api-2.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\geronimo\\specs\\geronimo-jta_1.1_spec\\1.1.1\\geronimo-jta_1.1_spec-1.1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\mail\\mail\\1.4.1\\mail-1.4.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\activation\\activation\\1.1\\activation-1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\geronimo\\specs\\geronimo-jaspic_1.0_spec\\1.0\\geronimo-jaspic_1.0_spec-1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\geronimo\\specs\\geronimo-annotation_1.0_spec\\1.1.1\\geronimo-annotation_1.0_spec-1.1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\asm\\asm-commons\\3.1\\asm-commons-3.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\asm\\asm-tree\\3.1\\asm-tree-3.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\asm\\asm\\3.1\\asm-3.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\thrift\\libfb303\\0.9.0\\libfb303-0.9.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\hive-serde\\1.0.1\\hive-serde-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\net\\sf\\opencsv\\opencsv\\2.3\\opencsv-2.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\hive-metastore\\1.0.1\\hive-metastore-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\jolbox\\bonecp\\0.8.0.RELEASE\\bonecp-0.8.0.RELEASE.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\derby\\derby\\10.10.1.1\\derby-10.10.1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\datanucleus\\datanucleus-api-jdo\\3.2.6\\datanucleus-api-jdo-3.2.6.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\datanucleus\\datanucleus-core\\3.2.10\\datanucleus-core-3.2.10.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\datanucleus\\datanucleus-rdbms\\3.2.9\\datanucleus-rdbms-3.2.9.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-pool\\commons-pool\\1.5.4\\commons-pool-1.5.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-dbcp\\commons-dbcp\\1.4\\commons-dbcp-1.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\jdo\\jdo-api\\3.0.1\\jdo-api-3.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\javax\\transaction\\jta\\1.1\\jta-1.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\antlr\\antlr-runtime\\3.4\\antlr-runtime-3.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\antlr\\stringtemplate\\3.2.1\\stringtemplate-3.2.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\antlr\\antlr\\2.7.7\\antlr-2.7.7.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\hive-shims\\1.0.1\\hive-shims-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\shims\\hive-shims-common\\1.0.1\\hive-shims-common-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\shims\\hive-shims-0.20\\1.0.1\\hive-shims-0.20-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\shims\\hive-shims-common-secure\\1.0.1\\hive-shims-common-secure-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\shims\\hive-shims-0.20S\\1.0.1\\hive-shims-0.20S-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\hive\\shims\\hive-shims-0.23\\1.0.1\\hive-shims-0.23-1.0.1.jar",
				"C:\\Users\\anand\\.m2\\repository\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\httpcomponents\\httpclient\\4.2.5\\httpclient-4.2.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\httpcomponents\\httpcore\\4.2.5\\httpcore-4.2.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\thrift\\libthrift\\0.9.0\\libthrift-0.9.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\zookeeper\\zookeeper\\3.4.5\\zookeeper-3.4.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\jline\\jline\\0.9.94\\jline-0.9.94.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\curator\\curator-framework\\2.6.0\\curator-framework-2.6.0.jar",
				"C:\\Program Files\\Java\\jdk1.8.0_131\\lib\\tools.jar",
				"C:\\Users\\anand\\.m2\\repository\\joda-time\\joda-time\\2.9.9\\joda-time-2.9.9.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\samba\\jcifs\\jcifs\\1.3.14-kohsuke-1\\jcifs-1.3.14-kohsuke-1.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\googlecode\\cqengine\\cqengine\\2.12.4\\cqengine-2.12.4.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\apache\\xmlbeans\\xmlbeans\\2.5.0\\xmlbeans-2.5.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\javassist\\javassist\\3.18.2-GA\\javassist-3.18.2-GA.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\antlr\\antlr4-runtime\\4.5\\antlr4-runtime-4.5.jar",
				"C:\\Users\\anand\\.m2\\repository\\junit\\junit\\4.11\\junit-4.11.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\hamcrest\\hamcrest-all\\1.3\\hamcrest-all-1.3.jar",
				"C:\\Users\\anand\\.m2\\repository\\com\\eqtechnologic\\eqube\\platform\\thirdparty\\junitutils\\1.0\\junitutils-1.0.jar",
				"C:\\Users\\anand\\.m2\\repository\\log4j\\log4j\\1.2.17\\log4j-1.2.17.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\slf4j\\slf4j-api\\1.7.7\\slf4j-api-1.7.7.jar",
				"C:\\Users\\anand\\.m2\\repository\\org\\slf4j\\slf4j-log4j12\\1.6.6\\slf4j-log4j12-1.6.6.jar" };

		String destFolder = "C:\\Users\\anand\\Desktop\\New folder\\jars\\";
		for (int i = 0; i < jarNames.length; i++) {
			File source = new File(jarNames[i]);
			System.out.println("<name>"+source.getName()+"</name>");
//			File destination = new File(destFolder + source.getName());
//
//			try {
//				Files.copy(source.toPath(), destination.toPath());
//			} catch (IOException e) {
//				e.printStackTrace();
//			}
		}

	}

}
